"use client";

// components/ResultCard.tsx
// Pure display component — receives a ScoreResponse from the parent dashboard
// after ScoreForm calls onResult(). No API calls are made here.
// All data originates from POST /score via api/main.py → phase6/ensemble.py.

import { ScoreResponse, Decision } from "@/types";

// ── Props ─────────────────────────────────────────────────────────────────────
// result: ScoreResponse — the full ensemble output passed down from dashboard state
// This is populated once ScoreForm successfully calls scoreTransaction()
interface ResultCardProps {
  result: ScoreResponse;
}

// ── Decision colour map ───────────────────────────────────────────────────────
// Maps each Decision value to its Tailwind class set — consistent across all components
// APPROVE = green, CHALLENGE = yellow, BLOCK = red (project-wide convention)
const DECISION_STYLES: Record<Decision, { badge: string; border: string; glow: string }> = {
  APPROVE:   {
    badge:  "text-green-400 bg-green-900/40 border-green-700",
    border: "border-green-700/50",
    glow:   "shadow-green-900/40",
  },
  CHALLENGE: {
    badge:  "text-yellow-400 bg-yellow-900/40 border-yellow-700",
    border: "border-yellow-700/50",
    glow:   "shadow-yellow-900/40",
  },
  BLOCK:     {
    badge:  "text-red-400 bg-red-900/40 border-red-700",
    border: "border-red-700/50",
    glow:   "shadow-red-900/40",
  },
};

// ── Helper — format a 0.0–1.0 float as a percentage string ───────────────────
// Used for ensemble_score, fraud_probability, anomaly_score, norm_* fields
// Multiplies by 100 and rounds to one decimal place
const pct = (val: number) => `${(val * 100).toFixed(1)}%`;

// ── Helper — format a risk score (0–100 integer from rule engine) ─────────────
// risk_score comes from the rule engine and is already on a 0–100 scale
// Displayed with one decimal place for consistency
const riskFmt = (val: number) => val.toFixed(1);

export default function ResultCard({ result }: ResultCardProps) {

  // ── Destructure all fields from ScoreResponse ─────────────────────────────
  // Data flows in from dashboard state → this component via props
  // Fields sourced from POST /score response (see api/models.py ScoreResponse)
  const {
    final_decision,
    ensemble_score,
    risk_score,
    fraud_probability,
    anomaly_score,
    is_anomaly,
    reason_codes,
    norm_rule,
    norm_zscore,
    norm_rf,
    weights,
    transaction_id,
  } = result;

  // ── Look up colour classes for this decision ──────────────────────────────
  // Resolves once per render — decision is fixed after scoring completes
  // Used across the badge, card border, and section accents
  const styles = DECISION_STYLES[final_decision];

  // ── Render ────────────────────────────────────────────────────────────────
  return (
    <div
      className={`bg-gray-900 border ${styles.border} rounded-2xl p-6 shadow-xl ${styles.glow} shadow-lg`}
    >

      {/* ── Header — Transaction ID + Decision Badge ─────────────────────── */}
      {/* transaction_id comes from ScoreResponse — generated by api/main.py  */}
      {/* final_decision is the ensemble output: APPROVE / CHALLENGE / BLOCK  */}
      <div className="flex items-start justify-between mb-6">
        <div>
          <h2 className="text-lg font-semibold text-white tracking-tight">
            Ensemble Result
          </h2>
          <p className="text-xs text-gray-500 mt-0.5 font-mono">
            {transaction_id}
          </p>
        </div>
        <span
          className={`text-sm font-bold px-4 py-1.5 rounded-full border tracking-widest uppercase ${styles.badge}`}
        >
          {final_decision}
        </span>
      </div>

      {/* ── Ensemble Score — primary metric ──────────────────────────────── */}
      {/* ensemble_score is the weighted combination of all three models       */}
      {/* Computed in phase6/ensemble.py — RF×0.50 + Rule×0.35 + ZScore×0.15  */}
      <div className="flex flex-col items-center justify-center py-4 mb-6">
        <p className="text-xs text-gray-500 uppercase tracking-widest mb-1">
          Ensemble Score
        </p>
        <p className={`text-6xl font-black tracking-tight ${
          final_decision === "APPROVE" ? "text-green-400" :
          final_decision === "CHALLENGE" ? "text-yellow-400" : "text-red-400"
        }`}>
          {pct(ensemble_score)}
        </p>
        <p className="text-xs text-gray-600 mt-1">weighted fraud probability</p>
      </div>

      {/* ── Three Sub-Scores ─────────────────────────────────────────────── */}
      {/* Each model contributes one score to the ensemble                    */}
      {/* risk_score: rule engine (0–100), fraud_probability: RF (0–1),       */}
      {/* anomaly_score: Z-Score (0–1) — all sourced from ScoreResponse       */}
      <div className="grid grid-cols-3 gap-3 mb-6">

        {/* Rule Engine */}
        <div className="bg-gray-800 border border-gray-700 rounded-xl p-3 text-center">
          <p className="text-xs text-gray-500 uppercase tracking-wider mb-1">
            Rule Engine
          </p>
          <p className="text-xl font-bold text-white">{riskFmt(risk_score)}</p>
          <p className="text-xs text-gray-600">risk score</p>
        </div>

        {/* Random Forest */}
        <div className="bg-gray-800 border border-gray-700 rounded-xl p-3 text-center">
          <p className="text-xs text-gray-500 uppercase tracking-wider mb-1">
            Random Forest
          </p>
          <p className="text-xl font-bold text-white">{pct(fraud_probability)}</p>
          <p className="text-xs text-gray-600">fraud prob.</p>
        </div>

        {/* Z-Score */}
        <div className="bg-gray-800 border border-gray-700 rounded-xl p-3 text-center">
          <p className="text-xs text-gray-500 uppercase tracking-wider mb-1">
            Z-Score
          </p>
          <p className={`text-xl font-bold ${is_anomaly ? "text-yellow-400" : "text-white"}`}>
            {pct(anomaly_score)}
          </p>
          <p className={`text-xs ${is_anomaly ? "text-yellow-600" : "text-gray-600"}`}>
            {is_anomaly ? "anomaly detected" : "no anomaly"}
          </p>
        </div>

      </div>

      {/* ── Reason Codes ─────────────────────────────────────────────────── */}
      {/* reason_codes is string[] from /score (differs from /alerts string)  */}
      {/* Each entry is a flag raised by the rule engine or ensemble logic     */}
      {reason_codes.length > 0 && (
        <div className="mb-6">
          <p className="text-xs text-gray-500 uppercase tracking-widest mb-2">
            Reason Codes
          </p>
          <div className="flex flex-wrap gap-2">
            {reason_codes.map((code, i) => (
              <span
                key={i}
                className="text-xs font-medium px-3 py-1 rounded-full bg-gray-800 border border-gray-600 text-gray-300"
              >
                {code}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* ── Normalised Weights Breakdown ─────────────────────────────────── */}
      {/* norm_rule, norm_zscore, norm_rf are each model's normalised score   */}
      {/* weights come from ScoreResponse.weights (Record<string, number>)    */}
      {/* Shows how each model contributed to the final ensemble score        */}
      <div>
        <p className="text-xs text-gray-500 uppercase tracking-widest mb-3">
          Model Contributions
        </p>
        <div className="space-y-2">

          {/* Rule Engine contribution */}
          <div className="flex items-center justify-between text-sm">
            <span className="text-gray-400 w-32">Rule Engine</span>
            <div className="flex-1 mx-3 bg-gray-800 rounded-full h-1.5">
              <div
                className="bg-blue-500 h-1.5 rounded-full transition-all"
                style={{ width: `${norm_rule * 100}%` }}
              />
            </div>
            <span className="text-gray-300 font-mono text-xs w-12 text-right">
              {pct(norm_rule)}
            </span>
            <span className="text-gray-600 font-mono text-xs w-16 text-right">
              ×{((weights["rule_engine"] ?? 0) * 100).toFixed(0)}%
            </span>
          </div>

          {/* Random Forest contribution */}
          <div className="flex items-center justify-between text-sm">
            <span className="text-gray-400 w-32">Random Forest</span>
            <div className="flex-1 mx-3 bg-gray-800 rounded-full h-1.5">
              <div
                className="bg-blue-500 h-1.5 rounded-full transition-all"
                style={{ width: `${norm_rf * 100}%` }}
              />
            </div>
            <span className="text-gray-300 font-mono text-xs w-12 text-right">
              {pct(norm_rf)}
            </span>
            <span className="text-gray-600 font-mono text-xs w-16 text-right">
              ×{((weights["random_forest"] ?? 0) * 100).toFixed(0)}%
            </span>
          </div>

          {/* Z-Score contribution */}
          <div className="flex items-center justify-between text-sm">
            <span className="text-gray-400 w-32">Z-Score</span>
            <div className="flex-1 mx-3 bg-gray-800 rounded-full h-1.5">
              <div
                className="bg-blue-500 h-1.5 rounded-full transition-all"
                style={{ width: `${norm_zscore * 100}%` }}
              />
            </div>
            <span className="text-gray-300 font-mono text-xs w-12 text-right">
              {pct(norm_zscore)}
            </span>
            <span className="text-gray-600 font-mono text-xs w-16 text-right">
              ×{((weights["zscore"] ?? 0) * 100).toFixed(0)}%
            </span>
          </div>

        </div>
      </div>

    </div>
  );
}